#!/usr/bin/env python3
"""Validate SDAtlas schema-v5 sources and deterministic build artifacts.

The maintained source is split in two layers:

* ``data/catalog.json`` contains ``meta`` and the unified A–E taxonomy;
* ``data/papers/*.json`` contains one independently editable paper per file.

``data/catalog.generated.json`` and ``assets/js/data.js`` are generated by
``scripts/sync_catalog.py``.  This checker validates both the source records
and the derived ``institutions``, ``subproblemCodes`` and ``citedBy`` fields.
It intentionally has no dependency on historical spreadsheets or tag files.

Run from either the repository root or the SDAtlas directory:

    python3 SDAtlas/scripts/validate_catalog.py
    python3 scripts/validate_catalog.py
"""

import json
import re
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any, Dict, List

from sync_catalog import build_catalog, render_aggregate, render_runtime


ROOT = Path(__file__).resolve().parents[1]
CATALOG_PATH = ROOT / "data" / "catalog.json"
PAPERS_DIR = ROOT / "data" / "papers"
PAPER_TEMPLATE_PATH = ROOT / "data" / "paper-template.json"
AGGREGATE_PATH = ROOT / "data" / "catalog.generated.json"
RUNTIME_CATALOG_PATH = ROOT / "assets" / "js" / "data.js"
EXPECTED_SUBPROBLEM_CODES = ["A", "B", "C", "D", "E"]
HTTP_PREFIXES = ("https://", "http://")
PROBLEM_FIELDS = ("background", "priorLimitation", "goal")
METHOD_COMPONENT_FIELDS = ("name", "stage", "purpose", "mechanism", "differenceFromPrior")
CHARACTERISTIC_BOOLEAN_FIELDS = (
    "requiresTraining", "usesTargetFeatures", "dynamicDraftLength",
    "dynamicVerifyLength", "lossless",
)
CHARACTERISTIC_ENUMS = {
    "drafterType": {
        "small-llm", "feature-drafter", "multi-token-head", "block-diffusion",
        "semi-autoregressive", "retrieval-based", "no-separate-drafter", "hybrid",
    },
    "draftGeneration": {"autoregressive", "parallel", "semi-autoregressive", "iterative", "none"},
    "candidateStructure": {"chain", "tree", "multiple-chains", "token-heads", "adaptive-tree", "none"},
    "verificationStrategy": {
        "fixed-prefix", "dynamic-prefix", "tree-verification", "batch-aware",
        "confidence-based", "custom",
    },
}
EVALUATION_FIELDS = (
    "targetModels", "benchmarks", "baselines", "metrics", "hardware", "frameworks",
)
RELATION_FIELDS = ("extends", "comparesAgainst", "related", "compatibleWith")
REPRODUCIBILITY_STATUSES = {
    "not-checked", "code-available", "not-reproduced", "reading-code",
    "partial", "reproduced", "failed",
}
LIMITATION_TYPES = {
    "algorithmic", "system", "training-cost", "memory", "latency",
    "evaluation", "generalization", "deployment", "evidence",
}
LIMITATION_SOURCE_TYPES = {"paper", "analysis", "observed-data"}
EVIDENCE_TYPES = {
    "method", "configuration", "result", "ablation", "limitation", "training", "system",
}
EXPECTED_PAPER_FIELDS = (
    "id", "index", "title", "shortName", "authors", "venue", "date", "url",
    "localPdf", "explanationPage", "institutionDetails", "institutionSource",
    "methodOverview", "problemStatement", "methodComponents", "characteristics",
    "subproblemContributions", "training", "evaluation", "mainResults", "limitations",
    "relations", "citations", "reproducibility", "evidence", "notes", "provenance",
)


class Validation:
    """Collect every actionable error instead of stopping at the first one."""

    def __init__(self) -> None:
        self.errors = []  # type: List[str]
        self.warnings = []  # type: List[str]

    def check(self, condition: bool, message: str) -> None:
        if not condition:
            self.errors.append(message)

    def warn(self, condition: bool, message: str) -> None:
        if not condition:
            self.warnings.append(message)


def read_object(path: Path) -> Dict[str, Any]:
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError(f"{path.relative_to(ROOT)} 必须是 JSON object")
    return value


def load_paper_sources() -> List[Dict[str, Any]]:
    if not PAPERS_DIR.is_dir():
        raise ValueError("data/papers 目录不存在")

    papers = []  # type: List[Dict[str, Any]]
    for path in sorted(PAPERS_DIR.glob("*.json")):
        paper = read_object(path)
        paper["_sourcePath"] = str(path.relative_to(ROOT))
        papers.append(paper)

    def order_key(paper: Dict[str, Any]) -> Any:
        index = paper.get("index")
        return (index if type(index) is int else 10**9, str(paper.get("id", "")))

    return sorted(papers, key=order_key)


def nonempty_text(value: Any) -> bool:
    return isinstance(value, str) and bool(value.strip())


def valid_http_url(value: Any) -> bool:
    return nonempty_text(value) and value.startswith(HTTP_PREFIXES)


def institution_summary(details: List[Dict[str, Any]]) -> str:
    """Apply the same stable display rule as the catalog builder."""
    groups = []  # type: List[List[str]]
    previous_order = None
    for item in details:
        order = item.get("order")
        if order != previous_order:
            groups.append([])
            previous_order = order
        groups[-1].append(str(item.get("name", "")))
    return " → ".join("、".join(group) for group in groups)


def validate_taxonomy(catalog: Dict[str, Any], result: Validation) -> List[str]:
    result.check(catalog.get("schemaVersion") == 5, "data/catalog.json schemaVersion 必须为 5")
    result.check("papers" not in catalog, "论文必须维护在 data/papers/*.json，不能内嵌到 catalog.json")
    result.check("categories" not in catalog and "tags" not in catalog,
                 "schema v5 只使用统一的 subproblems，不再使用 categories / tags")

    meta = catalog.get("meta")
    result.check(isinstance(meta, dict), "catalog.meta 必须是 object")
    if isinstance(meta, dict):
        for field in ("title", "shortTitle", "subtitle", "updated", "citationScope"):
            result.check(nonempty_text(meta.get(field)), f"catalog.meta.{field} 不能为空")
        result.check(meta.get("catalogFile") == "data/catalog.generated.json",
                     "meta.catalogFile 必须指向 data/catalog.generated.json")
        result.check(meta.get("paperDirectory") == "data/papers",
                     "meta.paperDirectory 必须指向 data/papers")
        result.check(meta.get("paperTemplate") == "data/paper-template.json",
                     "meta.paperTemplate 必须指向 data/paper-template.json")

    subproblems = catalog.get("subproblems")
    result.check(isinstance(subproblems, list), "catalog.subproblems 必须是 array")
    if not isinstance(subproblems, list):
        return []

    codes = [item.get("code") if isinstance(item, dict) else None for item in subproblems]
    result.check(codes == EXPECTED_SUBPROBLEM_CODES,
                 "统一子问题必须按 A、B、C、D、E 排列且各出现一次")
    ids = [item.get("id") if isinstance(item, dict) else None for item in subproblems]
    valid_ids = all(nonempty_text(value) for value in ids)
    result.check(valid_ids, "每个子问题都必须有非空 id")
    if valid_ids:
        result.check(len(ids) == len(set(ids)), "子问题 id 必须唯一")

    for index, item in enumerate(subproblems):
        label = f"subproblems[{index}]"
        result.check(isinstance(item, dict), f"{label} 必须是 object")
        if not isinstance(item, dict):
            continue
        for field in ("code", "id", "name", "shortName", "question", "description"):
            result.check(nonempty_text(item.get(field)), f"{label}.{field} 不能为空")
        for field in ("color", "softColor"):
            value = item.get(field)
            result.check(isinstance(value, str) and bool(re.fullmatch(r"#[0-9a-fA-F]{6}", value)),
                         f"{label}.{field} 必须是六位十六进制颜色")
    return [code for code in codes if isinstance(code, str)]


def validate_template(template: Dict[str, Any], result: Validation) -> None:
    """Keep every independently maintained paper aligned with one ordered template."""
    result.check(
        tuple(template) == EXPECTED_PAPER_FIELDS,
        "data/paper-template.json 的顶层字段或顺序与 schema v5 不一致",
    )


def validate_institutions(paper: Dict[str, Any], label: str, result: Validation) -> None:
    details = paper.get("institutionDetails")
    result.check(isinstance(details, list) and bool(details),
                 f"{label}: institutionDetails 必须是非空 array")
    if not isinstance(details, list) or not details:
        return

    valid_rows = [item for item in details if isinstance(item, dict)]
    result.check(len(valid_rows) == len(details), f"{label}: 每条单位明细必须是 object")
    if len(valid_rows) != len(details):
        return

    names = [item.get("name") for item in valid_rows]
    orders = [item.get("order") for item in valid_rows]
    valid_names = all(nonempty_text(name) for name in names)
    result.check(valid_names, f"{label}: 单位名称不能为空")
    if valid_names:
        result.check(len(names) == len(set(names)), f"{label}: 单位名称在论文内必须唯一")
    result.check(all(type(order) is int and order > 0 for order in orders),
                 f"{label}: 单位 order 必须是正整数")
    if all(type(order) is int and order > 0 for order in orders):
        result.check(orders == sorted(orders), f"{label}: 单位必须按 order 非降序排列")
        result.check(sorted(set(orders)) == list(range(1, max(orders) + 1)),
                     f"{label}: 单位 order 必须从 1 连续编号")
    result.check(all(nonempty_text(item.get("explanation")) for item in valid_rows),
                 f"{label}: 每个单位都必须有 explanation")
    result.check(valid_http_url(paper.get("institutionSource")),
                 f"{label}: institutionSource 必须是 HTTP(S) 来源")


def validate_local_pdf(paper: Dict[str, Any], label: str, result: Validation) -> None:
    result.check("localPdf" in paper, f"{label}: 必须显式提供 localPdf（未知时写 null）")
    result.check("localPdfNote" not in paper,
                 f"{label}: localPdfNote 已停用；没有本地文件时将 localPdf 写为 null")
    local_pdf = paper.get("localPdf")
    if local_pdf is None or local_pdf == "":
        result.check(local_pdf is None, f"{label}: 未知文本值应使用 null，不能使用空字符串")
        return

    result.check(nonempty_text(local_pdf), f"{label}: localPdf 必须是非空相对路径")
    if not nonempty_text(local_pdf):
        return
    path = Path(local_pdf)
    result.check(not path.is_absolute(), f"{label}: localPdf 必须使用相对路径")
    result.check(path.suffix.lower() == ".pdf", f"{label}: localPdf 必须指向 PDF")
    result.check((ROOT / path).resolve().is_file(), f"{label}: 本地 PDF 不存在：{local_pdf}")


def validate_explanation_page(paper: Dict[str, Any], label: str, result: Validation) -> None:
    """Validate the optional, reader-facing standalone HTML explanation."""
    if "explanationPage" not in paper or paper.get("explanationPage") is None:
        return

    value = paper.get("explanationPage")
    result.check(nonempty_text(value), f"{label}: explanationPage 必须是非空相对路径")
    if not nonempty_text(value):
        return

    path = Path(value)
    resolved = (ROOT / path).resolve()
    try:
        resolved.relative_to(ROOT.resolve())
        inside_root = True
    except ValueError:
        inside_root = False
    result.check(not path.is_absolute(), f"{label}: explanationPage 必须相对于 SDAtlas/")
    result.check(path.suffix.lower() == ".html", f"{label}: explanationPage 必须指向 HTML")
    result.check(inside_root, f"{label}: explanationPage 不能指向 SDAtlas/ 之外")
    result.check(resolved.is_file(), f"{label}: 论文解读专题页不存在：{value}")


def validate_nullable_text(value: Any, label: str, result: Validation) -> None:
    """Accept a meaningful string or the schema-v5 unknown marker ``null``."""
    result.check(value is None or nonempty_text(value), f"{label} 必须是非空字符串或 null")


def validate_string_array(value: Any, label: str, result: Validation) -> None:
    result.check(isinstance(value, list), f"{label} 必须是 array")
    if not isinstance(value, list):
        return
    valid_items = all(nonempty_text(item) for item in value)
    result.check(valid_items, f"{label} 只能包含非空字符串")
    if valid_items:
        result.check(len(value) == len(set(value)), f"{label} 不能包含重复项")


def validate_exact_object(
    value: Any, fields: Any, label: str, result: Validation
) -> Any:
    """Validate one fixed-shape nested object and return it when usable."""
    result.check(isinstance(value, dict), f"{label} 必须是 object")
    if not isinstance(value, dict):
        return None
    expected = set(fields)
    actual = set(value)
    result.check(actual == expected,
                 f"{label} 字段必须恰好为 {sorted(expected)}，当前差异为 {sorted(actual ^ expected)}")
    return value


def validate_problem_statement(paper: Dict[str, Any], label: str, result: Validation) -> None:
    value = validate_exact_object(
        paper.get("problemStatement"), PROBLEM_FIELDS,
        f"{label}: problemStatement", result,
    )
    if value is None:
        return
    for field in PROBLEM_FIELDS:
        validate_nullable_text(value.get(field), f"{label}: problemStatement.{field}", result)


def validate_method_components(paper: Dict[str, Any], label: str, result: Validation) -> None:
    components = paper.get("methodComponents")
    result.check(isinstance(components, list), f"{label}: methodComponents 必须是 array")
    if not isinstance(components, list):
        return
    for index, component in enumerate(components):
        component_label = f"{label}: methodComponents[{index}]"
        value = validate_exact_object(
            component, METHOD_COMPONENT_FIELDS, component_label, result,
        )
        if value is None:
            continue
        for field in ("name", "stage", "purpose", "mechanism"):
            result.check(nonempty_text(value.get(field)), f"{component_label}.{field} 不能为空")
        validate_nullable_text(
            value.get("differenceFromPrior"),
            f"{component_label}.differenceFromPrior", result,
        )


def validate_characteristics(paper: Dict[str, Any], label: str, result: Validation) -> None:
    fields = CHARACTERISTIC_BOOLEAN_FIELDS + tuple(CHARACTERISTIC_ENUMS)
    value = validate_exact_object(
        paper.get("characteristics"), fields, f"{label}: characteristics", result,
    )
    if value is None:
        return
    for field in CHARACTERISTIC_BOOLEAN_FIELDS:
        item = value.get(field)
        result.check(item is None or type(item) is bool,
                     f"{label}: characteristics.{field} 必须是 boolean 或 null")
    for field, allowed in CHARACTERISTIC_ENUMS.items():
        item = value.get(field)
        result.check(item is None or item in allowed,
                     f"{label}: characteristics.{field} 值无效：{item!r}")


def validate_training(paper: Dict[str, Any], label: str, result: Validation) -> None:
    value = validate_exact_object(
        paper.get("training"), ("summary", "data", "objective"),
        f"{label}: training", result,
    )
    if value is None:
        return
    for field in ("summary", "data", "objective"):
        validate_nullable_text(value.get(field), f"{label}: training.{field}", result)


def validate_evaluation(paper: Dict[str, Any], label: str, result: Validation) -> None:
    value = validate_exact_object(
        paper.get("evaluation"), EVALUATION_FIELDS,
        f"{label}: evaluation", result,
    )
    if value is None:
        return
    for field in EVALUATION_FIELDS:
        validate_string_array(value.get(field), f"{label}: evaluation.{field}", result)


def validate_main_results(paper: Dict[str, Any], label: str, result: Validation) -> None:
    values = paper.get("mainResults")
    result.check(isinstance(values, list), f"{label}: mainResults 必须是 array")
    if not isinstance(values, list):
        return
    fields = ("condition", "metric", "result", "comparison", "source")
    for index, item in enumerate(values):
        item_label = f"{label}: mainResults[{index}]"
        value = validate_exact_object(item, fields, item_label, result)
        if value is not None:
            for field in fields:
                result.check(nonempty_text(value.get(field)), f"{item_label}.{field} 不能为空")


def validate_limitations(paper: Dict[str, Any], label: str, result: Validation) -> None:
    values = paper.get("limitations")
    result.check(isinstance(values, list), f"{label}: limitations 必须是 array")
    if not isinstance(values, list):
        return
    fields = ("type", "description", "sourceType")
    for index, item in enumerate(values):
        item_label = f"{label}: limitations[{index}]"
        value = validate_exact_object(item, fields, item_label, result)
        if value is None:
            continue
        result.check(value.get("type") in LIMITATION_TYPES,
                     f"{item_label}.type 值无效：{value.get('type')!r}")
        result.check(nonempty_text(value.get("description")),
                     f"{item_label}.description 不能为空")
        result.check(value.get("sourceType") in LIMITATION_SOURCE_TYPES,
                     f"{item_label}.sourceType 值无效：{value.get('sourceType')!r}")


def validate_relations(
    paper: Dict[str, Any], label: str, valid_ids: Any, result: Validation
) -> None:
    value = validate_exact_object(
        paper.get("relations"), RELATION_FIELDS, f"{label}: relations", result,
    )
    if value is None:
        return
    paper_id = paper.get("id")
    for field in RELATION_FIELDS:
        relation_label = f"{label}: relations.{field}"
        targets = value.get(field)
        validate_string_array(targets, relation_label, result)
        if not isinstance(targets, list):
            continue
        result.check(paper_id not in targets, f"{relation_label} 不能包含自身")
        unknown = set(targets) - valid_ids
        result.check(not unknown, f"{relation_label} 包含未收录论文 {sorted(unknown)}")


def validate_reproducibility(paper: Dict[str, Any], label: str, result: Validation) -> None:
    fields = (
        "codeUrl", "modelUrl", "projectPage", "officialImplementation", "status", "notes",
    )
    value = validate_exact_object(
        paper.get("reproducibility"), fields,
        f"{label}: reproducibility", result,
    )
    if value is None:
        return
    for field in ("codeUrl", "modelUrl", "projectPage"):
        item = value.get(field)
        result.check(item is None or valid_http_url(item),
                     f"{label}: reproducibility.{field} 必须是 HTTP(S) URL 或 null")
    official = value.get("officialImplementation")
    result.check(official is None or type(official) is bool,
                 f"{label}: reproducibility.officialImplementation 必须是 boolean 或 null")
    result.check(value.get("status") in REPRODUCIBILITY_STATUSES,
                 f"{label}: reproducibility.status 值无效：{value.get('status')!r}")
    validate_string_array(value.get("notes"), f"{label}: reproducibility.notes", result)


def validate_evidence(paper: Dict[str, Any], label: str, result: Validation) -> None:
    values = paper.get("evidence")
    result.check(isinstance(values, list), f"{label}: evidence 必须是 array")
    if not isinstance(values, list):
        return
    fields = ("claim", "location", "type")
    for index, item in enumerate(values):
        item_label = f"{label}: evidence[{index}]"
        value = validate_exact_object(item, fields, item_label, result)
        if value is None:
            continue
        result.check(nonempty_text(value.get("claim")), f"{item_label}.claim 不能为空")
        result.check(nonempty_text(value.get("location")), f"{item_label}.location 不能为空")
        result.check(value.get("type") in EVIDENCE_TYPES,
                     f"{item_label}.type 值无效：{value.get('type')!r}")


def validate_provenance(paper: Dict[str, Any], label: str, result: Validation) -> None:
    value = validate_exact_object(
        paper.get("provenance"), ("legacyWorkbookRow", "workbookInstitutions"),
        f"{label}: provenance", result,
    )
    if value is None:
        return
    row = value.get("legacyWorkbookRow")
    result.check(row is None or (type(row) is int and row > 0),
                 f"{label}: provenance.legacyWorkbookRow 必须是正整数或 null")
    validate_nullable_text(
        value.get("workbookInstitutions"),
        f"{label}: provenance.workbookInstitutions", result,
    )


def validate_papers(
    papers: List[Dict[str, Any]], valid_codes: List[str], result: Validation
) -> None:
    result.check(bool(papers), "data/papers 至少需要一篇论文")
    ids = [paper.get("id") for paper in papers]
    indices = [paper.get("index") for paper in papers]
    valid_ids = all(nonempty_text(paper_id) for paper_id in ids)
    result.check(valid_ids, "每篇论文都必须有非空 id")
    if valid_ids:
        result.check(len(ids) == len(set(ids)), "论文 id 必须唯一")
    result.check(all(type(index) is int for index in indices), "论文 index 必须是整数")
    result.check(indices == list(range(1, len(papers) + 1)), "论文 index 必须连续排列为 1..N")

    valid_id_set = {paper_id for paper_id in ids if isinstance(paper_id, str)}
    valid_code_set = set(valid_codes)
    covered_codes = set()

    for paper in papers:
        paper_id = paper.get("id")
        index = paper.get("index")
        label = f"#{index} {paper_id}"
        source_path = Path(str(paper.get("_sourcePath", "")))
        source_fields = tuple(field for field in paper if field != "_sourcePath")
        result.check(source_fields == EXPECTED_PAPER_FIELDS,
                     f"{label}: 顶层字段及顺序必须与 data/paper-template.json 完全一致")
        result.check(source_path.stem == paper_id,
                     f"{label}: 文件名必须与 id 一致（当前为 {source_path.name}）")
        result.check(isinstance(paper_id, str) and bool(re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", paper_id)),
                     f"{label}: id 只能使用小写字母、数字和连字符")

        for field in ("title", "shortName", "methodOverview", "venue", "date", "url"):
            result.check(nonempty_text(paper.get(field)), f"{label}: {field} 不能为空")
        result.check(bool(re.fullmatch(r"\d{4}-(0[1-9]|1[0-2])", str(paper.get("date", "")))),
                     f"{label}: date 必须是有效的 YYYY-MM")
        result.check(valid_http_url(paper.get("url")), f"{label}: url 必须是 HTTP(S) 链接")

        authors = paper.get("authors")
        result.check(isinstance(authors, list) and bool(authors),
                     f"{label}: authors 必须是非空 array")
        if isinstance(authors, list):
            valid_authors = all(nonempty_text(author) for author in authors)
            result.check(valid_authors, f"{label}: authors 只能包含非空字符串")
            if valid_authors:
                result.check(len(authors) == len(set(authors)), f"{label}: authors 不能重复")

        notes = paper.get("notes")
        result.check(isinstance(notes, list), f"{label}: notes 必须是 array，可为空")
        if isinstance(notes, list):
            result.check(all(nonempty_text(note) for note in notes),
                         f"{label}: notes 中的每项必须是非空字符串")

        validate_institutions(paper, label, result)
        validate_problem_statement(paper, label, result)
        validate_method_components(paper, label, result)
        validate_characteristics(paper, label, result)

        contributions = paper.get("subproblemContributions")
        result.check(isinstance(contributions, dict) and bool(contributions),
                     f"{label}: subproblemContributions 必须是非空 object")
        if isinstance(contributions, dict):
            contribution_codes = set(contributions)
            covered_codes.update(contribution_codes)
            result.check(contribution_codes <= valid_code_set,
                         f"{label}: 包含不存在的子问题 {sorted(contribution_codes - valid_code_set)}")
            for code, contribution in contributions.items():
                contribution_label = f"{label}: subproblemContributions.{code}"
                result.check(isinstance(contribution, dict),
                             f"{contribution_label} 必须是包含 summary/detail 的 object")
                if isinstance(contribution, dict):
                    result.check(nonempty_text(contribution.get("summary")),
                                 f"{contribution_label}.summary 不能为空")
                    result.check(nonempty_text(contribution.get("detail")),
                                 f"{contribution_label}.detail 不能为空")

        validate_training(paper, label, result)
        validate_evaluation(paper, label, result)
        validate_main_results(paper, label, result)
        validate_limitations(paper, label, result)
        validate_relations(paper, label, valid_id_set, result)

        citations = paper.get("citations")
        result.check(isinstance(citations, list), f"{label}: citations 必须是 array，可为空")
        if isinstance(citations, list):
            valid_citations = all(nonempty_text(citation) for citation in citations)
            result.check(valid_citations, f"{label}: citations 只能包含非空论文 id")
            if valid_citations:
                result.check(len(citations) == len(set(citations)), f"{label}: citations 不能重复")
                result.check(paper_id not in citations, f"{label}: citations 不能包含自身")
                unknown = set(citations) - valid_id_set
                result.check(not unknown, f"{label}: citations 包含未收录论文 {sorted(unknown)}")

        for derived_field in ("institutions", "subproblemCodes", "citedBy"):
            result.check(derived_field not in paper,
                         f"{label}: {derived_field} 是生成字段，不能写入论文源文件")
        validate_reproducibility(paper, label, result)
        validate_evidence(paper, label, result)
        validate_provenance(paper, label, result)
        validate_local_pdf(paper, label, result)
        validate_explanation_page(paper, label, result)

    result.check(covered_codes == valid_code_set,
                 f"A–E 每个子问题都应至少有一篇论文，当前缺少 {sorted(valid_code_set - covered_codes)}")


def validate_generated(
    catalog: Dict[str, Any], papers: List[Dict[str, Any]], result: Validation
) -> None:
    """Check artifacts byte-for-byte and explicitly audit derived fields."""
    try:
        expected = build_catalog(catalog, papers)
    except (KeyError, TypeError, ValueError) as error:
        result.check(False, f"sync_catalog 无法从源文件构建目录：{error}")
        return

    result.check(AGGREGATE_PATH.is_file(), "缺少生成文件 data/catalog.generated.json")
    result.check(RUNTIME_CATALOG_PATH.is_file(), "缺少生成文件 assets/js/data.js")
    if AGGREGATE_PATH.is_file():
        result.check(AGGREGATE_PATH.read_text(encoding="utf-8") == render_aggregate(expected),
                     "data/catalog.generated.json 未同步；请运行 scripts/sync_catalog.py")
    if RUNTIME_CATALOG_PATH.is_file():
        result.check(RUNTIME_CATALOG_PATH.read_text(encoding="utf-8") == render_runtime(expected),
                     "assets/js/data.js 未同步；请运行 scripts/sync_catalog.py")

    if not AGGREGATE_PATH.is_file():
        return
    try:
        generated = read_object(AGGREGATE_PATH)
    except (OSError, ValueError, json.JSONDecodeError) as error:
        result.check(False, f"无法读取 data/catalog.generated.json：{error}")
        return

    generated_papers = generated.get("papers")
    result.check(isinstance(generated_papers, list), "生成目录 papers 必须是 array")
    if not isinstance(generated_papers, list):
        return
    by_id = {
        paper.get("id"): paper
        for paper in generated_papers
        if isinstance(paper, dict) and isinstance(paper.get("id"), str)
    }
    result.check([paper.get("id") for paper in generated_papers if isinstance(paper, dict)] ==
                 [paper.get("id") for paper in papers],
                 "生成目录的论文顺序必须与 index 顺序一致")

    reverse = defaultdict(list)  # type: Dict[str, List[str]]
    for source in papers:
        for cited_id in source.get("citations", []):
            reverse[cited_id].append(str(source.get("id")))

    for source in papers:
        paper_id = source.get("id")
        label = f"生成论文 {paper_id}"
        generated_paper = by_id.get(paper_id)
        result.check(isinstance(generated_paper, dict), f"{label}: 记录缺失")
        if not isinstance(generated_paper, dict):
            continue
        details = source.get("institutionDetails", [])
        if isinstance(details, list) and all(isinstance(item, dict) for item in details):
            result.check(generated_paper.get("institutions") == institution_summary(details),
                         f"{label}: institutions 未按单位顺位正确派生")
        contributions = source.get("subproblemContributions", {})
        if isinstance(contributions, dict):
            result.check(generated_paper.get("subproblemCodes") == list(contributions),
                         f"{label}: subproblemCodes 未由贡献键正确派生")
        result.check(generated_paper.get("citedBy") == reverse.get(str(paper_id), []),
                     f"{label}: citedBy 不是 citations 的正确反向关系")


def main() -> int:
    try:
        catalog = read_object(CATALOG_PATH)
        template = read_object(PAPER_TEMPLATE_PATH)
        papers = load_paper_sources()
    except (OSError, ValueError, json.JSONDecodeError) as error:
        print(f"[ERROR] 无法执行目录验证：{error}", file=sys.stderr)
        return 2

    result = Validation()
    valid_codes = validate_taxonomy(catalog, result)
    validate_template(template, result)
    validate_papers(papers, valid_codes, result)
    validate_generated(catalog, papers, result)

    for warning in result.warnings:
        print(f"[WARN] {warning}")
    for error in result.errors:
        print(f"[ERROR] {error}")

    if result.errors:
        print(f"\n目录验证失败：{len(result.errors)} 个错误，{len(result.warnings)} 个提醒。")
        return 1

    print(
        f"目录验证通过：{len(papers)} 篇独立论文、{len(valid_codes)} 个统一子问题；"
        "schema-v5 方法、特征、实验、关系、复现、证据、站内引用与两份生成物均一致。"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
