#!/usr/bin/env python3
"""Validate SDAtlas schema-v4 sources and deterministic build artifacts.

The maintained source is split in two layers:

* ``data/catalog.json`` contains ``meta`` and the unified A–E taxonomy;
* ``data/papers/*.json`` contains one independently editable paper per file.

``data/catalog.generated.json`` and ``assets/js/data.js`` are generated by
``scripts/sync_catalog.py``.  This checker validates both the source records
and the derived ``institutions``, ``subproblemCodes`` and ``citedBy`` fields.
It intentionally has no dependency on historical spreadsheets or tag files.

Run from either the repository root or the SDAtlas directory:

    python3 SDAtlas/scripts/validate_catalog.py
    python3 scripts/validate_catalog.py
"""

import json
import re
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any, Dict, List

from sync_catalog import build_catalog, render_aggregate, render_runtime


ROOT = Path(__file__).resolve().parents[1]
CATALOG_PATH = ROOT / "data" / "catalog.json"
PAPERS_DIR = ROOT / "data" / "papers"
AGGREGATE_PATH = ROOT / "data" / "catalog.generated.json"
RUNTIME_CATALOG_PATH = ROOT / "assets" / "js" / "data.js"
EXPECTED_SUBPROBLEM_CODES = ["A", "B", "C", "D", "E"]
HTTP_PREFIXES = ("https://", "http://")


class Validation:
    """Collect every actionable error instead of stopping at the first one."""

    def __init__(self) -> None:
        self.errors = []  # type: List[str]
        self.warnings = []  # type: List[str]

    def check(self, condition: bool, message: str) -> None:
        if not condition:
            self.errors.append(message)

    def warn(self, condition: bool, message: str) -> None:
        if not condition:
            self.warnings.append(message)


def read_object(path: Path) -> Dict[str, Any]:
    value = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(value, dict):
        raise ValueError(f"{path.relative_to(ROOT)} 必须是 JSON object")
    return value


def load_paper_sources() -> List[Dict[str, Any]]:
    if not PAPERS_DIR.is_dir():
        raise ValueError("data/papers 目录不存在")

    papers = []  # type: List[Dict[str, Any]]
    for path in sorted(PAPERS_DIR.glob("*.json")):
        paper = read_object(path)
        paper["_sourcePath"] = str(path.relative_to(ROOT))
        papers.append(paper)

    def order_key(paper: Dict[str, Any]) -> Any:
        index = paper.get("index")
        return (index if type(index) is int else 10**9, str(paper.get("id", "")))

    return sorted(papers, key=order_key)


def nonempty_text(value: Any) -> bool:
    return isinstance(value, str) and bool(value.strip())


def valid_http_url(value: Any) -> bool:
    return nonempty_text(value) and value.startswith(HTTP_PREFIXES)


def institution_summary(details: List[Dict[str, Any]]) -> str:
    """Apply the same stable display rule as the catalog builder."""
    groups = []  # type: List[List[str]]
    previous_order = None
    for item in details:
        order = item.get("order")
        if order != previous_order:
            groups.append([])
            previous_order = order
        groups[-1].append(str(item.get("name", "")))
    return " → ".join("、".join(group) for group in groups)


def validate_taxonomy(catalog: Dict[str, Any], result: Validation) -> List[str]:
    result.check(catalog.get("schemaVersion") == 4, "data/catalog.json schemaVersion 必须为 4")
    result.check("papers" not in catalog, "论文必须维护在 data/papers/*.json，不能内嵌到 catalog.json")
    result.check("categories" not in catalog and "tags" not in catalog,
                 "schema v4 只使用统一的 subproblems，不再使用 categories / tags")

    meta = catalog.get("meta")
    result.check(isinstance(meta, dict), "catalog.meta 必须是 object")
    if isinstance(meta, dict):
        for field in ("title", "shortTitle", "subtitle", "updated", "citationScope"):
            result.check(nonempty_text(meta.get(field)), f"catalog.meta.{field} 不能为空")
        result.check(meta.get("catalogFile") == "data/catalog.generated.json",
                     "meta.catalogFile 必须指向 data/catalog.generated.json")
        result.check(meta.get("paperDirectory") == "data/papers",
                     "meta.paperDirectory 必须指向 data/papers")
        result.check(meta.get("paperTemplate") == "data/paper-template.json",
                     "meta.paperTemplate 必须指向 data/paper-template.json")

    subproblems = catalog.get("subproblems")
    result.check(isinstance(subproblems, list), "catalog.subproblems 必须是 array")
    if not isinstance(subproblems, list):
        return []

    codes = [item.get("code") if isinstance(item, dict) else None for item in subproblems]
    result.check(codes == EXPECTED_SUBPROBLEM_CODES,
                 "统一子问题必须按 A、B、C、D、E 排列且各出现一次")
    ids = [item.get("id") if isinstance(item, dict) else None for item in subproblems]
    valid_ids = all(nonempty_text(value) for value in ids)
    result.check(valid_ids, "每个子问题都必须有非空 id")
    if valid_ids:
        result.check(len(ids) == len(set(ids)), "子问题 id 必须唯一")

    for index, item in enumerate(subproblems):
        label = f"subproblems[{index}]"
        result.check(isinstance(item, dict), f"{label} 必须是 object")
        if not isinstance(item, dict):
            continue
        for field in ("code", "id", "name", "shortName", "question", "description"):
            result.check(nonempty_text(item.get(field)), f"{label}.{field} 不能为空")
        for field in ("color", "softColor"):
            value = item.get(field)
            result.check(isinstance(value, str) and bool(re.fullmatch(r"#[0-9a-fA-F]{6}", value)),
                         f"{label}.{field} 必须是六位十六进制颜色")
    return [code for code in codes if isinstance(code, str)]


def validate_institutions(paper: Dict[str, Any], label: str, result: Validation) -> None:
    details = paper.get("institutionDetails")
    result.check(isinstance(details, list) and bool(details),
                 f"{label}: institutionDetails 必须是非空 array")
    if not isinstance(details, list) or not details:
        return

    valid_rows = [item for item in details if isinstance(item, dict)]
    result.check(len(valid_rows) == len(details), f"{label}: 每条单位明细必须是 object")
    if len(valid_rows) != len(details):
        return

    names = [item.get("name") for item in valid_rows]
    orders = [item.get("order") for item in valid_rows]
    valid_names = all(nonempty_text(name) for name in names)
    result.check(valid_names, f"{label}: 单位名称不能为空")
    if valid_names:
        result.check(len(names) == len(set(names)), f"{label}: 单位名称在论文内必须唯一")
    result.check(all(type(order) is int and order > 0 for order in orders),
                 f"{label}: 单位 order 必须是正整数")
    if all(type(order) is int and order > 0 for order in orders):
        result.check(orders == sorted(orders), f"{label}: 单位必须按 order 非降序排列")
        result.check(sorted(set(orders)) == list(range(1, max(orders) + 1)),
                     f"{label}: 单位 order 必须从 1 连续编号")
    result.check(all(nonempty_text(item.get("explanation")) for item in valid_rows),
                 f"{label}: 每个单位都必须有 explanation")
    result.check(valid_http_url(paper.get("institutionSource")),
                 f"{label}: institutionSource 必须是 HTTP(S) 来源")


def validate_local_pdf(paper: Dict[str, Any], label: str, result: Validation) -> None:
    local_pdf = paper.get("localPdf")
    local_note = paper.get("localPdfNote")
    if local_pdf is None or local_pdf == "":
        result.check(nonempty_text(local_note),
                     f"{label}: 没有 localPdf 时必须提供 localPdfNote")
        return

    result.check(nonempty_text(local_pdf), f"{label}: localPdf 必须是非空相对路径")
    if not nonempty_text(local_pdf):
        return
    path = Path(local_pdf)
    result.check(not path.is_absolute(), f"{label}: localPdf 必须使用相对路径")
    result.check(path.suffix.lower() == ".pdf", f"{label}: localPdf 必须指向 PDF")
    result.check((ROOT / path).resolve().is_file(), f"{label}: 本地 PDF 不存在：{local_pdf}")
    result.warn(not nonempty_text(local_note),
                f"{label}: 已有 localPdf，localPdfNote 通常应删除以免信息冲突")


def validate_papers(
    papers: List[Dict[str, Any]], valid_codes: List[str], result: Validation
) -> None:
    result.check(bool(papers), "data/papers 至少需要一篇论文")
    ids = [paper.get("id") for paper in papers]
    indices = [paper.get("index") for paper in papers]
    valid_ids = all(nonempty_text(paper_id) for paper_id in ids)
    result.check(valid_ids, "每篇论文都必须有非空 id")
    if valid_ids:
        result.check(len(ids) == len(set(ids)), "论文 id 必须唯一")
    result.check(all(type(index) is int for index in indices), "论文 index 必须是整数")
    result.check(indices == list(range(1, len(papers) + 1)), "论文 index 必须连续排列为 1..N")

    valid_id_set = {paper_id for paper_id in ids if isinstance(paper_id, str)}
    valid_code_set = set(valid_codes)
    covered_codes = set()

    for paper in papers:
        paper_id = paper.get("id")
        index = paper.get("index")
        label = f"#{index} {paper_id}"
        source_path = Path(str(paper.get("_sourcePath", "")))
        result.check(source_path.stem == paper_id,
                     f"{label}: 文件名必须与 id 一致（当前为 {source_path.name}）")
        result.check(isinstance(paper_id, str) and bool(re.fullmatch(r"[a-z0-9]+(?:-[a-z0-9]+)*", paper_id)),
                     f"{label}: id 只能使用小写字母、数字和连字符")

        for field in ("title", "shortName", "methodOverview", "venue", "date", "url"):
            result.check(nonempty_text(paper.get(field)), f"{label}: {field} 不能为空")
        result.check(bool(re.fullmatch(r"\d{4}-(0[1-9]|1[0-2])", str(paper.get("date", "")))),
                     f"{label}: date 必须是有效的 YYYY-MM")
        result.check(valid_http_url(paper.get("url")), f"{label}: url 必须是 HTTP(S) 链接")

        authors = paper.get("authors")
        result.check(isinstance(authors, list) and bool(authors),
                     f"{label}: authors 必须是非空 array")
        if isinstance(authors, list):
            valid_authors = all(nonempty_text(author) for author in authors)
            result.check(valid_authors, f"{label}: authors 只能包含非空字符串")
            if valid_authors:
                result.check(len(authors) == len(set(authors)), f"{label}: authors 不能重复")

        notes = paper.get("notes")
        result.check(isinstance(notes, list), f"{label}: notes 必须是 array，可为空")
        if isinstance(notes, list):
            result.check(all(nonempty_text(note) for note in notes),
                         f"{label}: notes 中的每项必须是非空字符串")

        validate_institutions(paper, label, result)

        contributions = paper.get("subproblemContributions")
        result.check(isinstance(contributions, dict) and bool(contributions),
                     f"{label}: subproblemContributions 必须是非空 object")
        if isinstance(contributions, dict):
            contribution_codes = set(contributions)
            covered_codes.update(contribution_codes)
            result.check(contribution_codes <= valid_code_set,
                         f"{label}: 包含不存在的子问题 {sorted(contribution_codes - valid_code_set)}")
            for code, contribution in contributions.items():
                contribution_label = f"{label}: subproblemContributions.{code}"
                result.check(isinstance(contribution, dict),
                             f"{contribution_label} 必须是包含 summary/detail 的 object")
                if isinstance(contribution, dict):
                    result.check(nonempty_text(contribution.get("summary")),
                                 f"{contribution_label}.summary 不能为空")
                    result.check(nonempty_text(contribution.get("detail")),
                                 f"{contribution_label}.detail 不能为空")

        citations = paper.get("citations")
        result.check(isinstance(citations, list), f"{label}: citations 必须是 array，可为空")
        if isinstance(citations, list):
            valid_citations = all(nonempty_text(citation) for citation in citations)
            result.check(valid_citations, f"{label}: citations 只能包含非空论文 id")
            if valid_citations:
                result.check(len(citations) == len(set(citations)), f"{label}: citations 不能重复")
                result.check(paper_id not in citations, f"{label}: citations 不能包含自身")
                unknown = set(citations) - valid_id_set
                result.check(not unknown, f"{label}: citations 包含未收录论文 {sorted(unknown)}")

        for derived_field in ("institutions", "subproblemCodes", "citedBy"):
            result.check(derived_field not in paper,
                         f"{label}: {derived_field} 是生成字段，不能写入论文源文件")
        validate_local_pdf(paper, label, result)

    result.check(covered_codes == valid_code_set,
                 f"A–E 每个子问题都应至少有一篇论文，当前缺少 {sorted(valid_code_set - covered_codes)}")


def validate_generated(
    catalog: Dict[str, Any], papers: List[Dict[str, Any]], result: Validation
) -> None:
    """Check artifacts byte-for-byte and explicitly audit derived fields."""
    try:
        expected = build_catalog(catalog, papers)
    except (KeyError, TypeError, ValueError) as error:
        result.check(False, f"sync_catalog 无法从源文件构建目录：{error}")
        return

    result.check(AGGREGATE_PATH.is_file(), "缺少生成文件 data/catalog.generated.json")
    result.check(RUNTIME_CATALOG_PATH.is_file(), "缺少生成文件 assets/js/data.js")
    if AGGREGATE_PATH.is_file():
        result.check(AGGREGATE_PATH.read_text(encoding="utf-8") == render_aggregate(expected),
                     "data/catalog.generated.json 未同步；请运行 scripts/sync_catalog.py")
    if RUNTIME_CATALOG_PATH.is_file():
        result.check(RUNTIME_CATALOG_PATH.read_text(encoding="utf-8") == render_runtime(expected),
                     "assets/js/data.js 未同步；请运行 scripts/sync_catalog.py")

    if not AGGREGATE_PATH.is_file():
        return
    try:
        generated = read_object(AGGREGATE_PATH)
    except (OSError, ValueError, json.JSONDecodeError) as error:
        result.check(False, f"无法读取 data/catalog.generated.json：{error}")
        return

    generated_papers = generated.get("papers")
    result.check(isinstance(generated_papers, list), "生成目录 papers 必须是 array")
    if not isinstance(generated_papers, list):
        return
    by_id = {
        paper.get("id"): paper
        for paper in generated_papers
        if isinstance(paper, dict) and isinstance(paper.get("id"), str)
    }
    result.check([paper.get("id") for paper in generated_papers if isinstance(paper, dict)] ==
                 [paper.get("id") for paper in papers],
                 "生成目录的论文顺序必须与 index 顺序一致")

    reverse = defaultdict(list)  # type: Dict[str, List[str]]
    for source in papers:
        for cited_id in source.get("citations", []):
            reverse[cited_id].append(str(source.get("id")))

    for source in papers:
        paper_id = source.get("id")
        label = f"生成论文 {paper_id}"
        generated_paper = by_id.get(paper_id)
        result.check(isinstance(generated_paper, dict), f"{label}: 记录缺失")
        if not isinstance(generated_paper, dict):
            continue
        details = source.get("institutionDetails", [])
        if isinstance(details, list) and all(isinstance(item, dict) for item in details):
            result.check(generated_paper.get("institutions") == institution_summary(details),
                         f"{label}: institutions 未按单位顺位正确派生")
        contributions = source.get("subproblemContributions", {})
        if isinstance(contributions, dict):
            result.check(generated_paper.get("subproblemCodes") == list(contributions),
                         f"{label}: subproblemCodes 未由贡献键正确派生")
        result.check(generated_paper.get("citedBy") == reverse.get(str(paper_id), []),
                     f"{label}: citedBy 不是 citations 的正确反向关系")


def main() -> int:
    try:
        catalog = read_object(CATALOG_PATH)
        papers = load_paper_sources()
    except (OSError, ValueError, json.JSONDecodeError) as error:
        print(f"[ERROR] 无法执行目录验证：{error}", file=sys.stderr)
        return 2

    result = Validation()
    valid_codes = validate_taxonomy(catalog, result)
    validate_papers(papers, valid_codes, result)
    validate_generated(catalog, papers, result)

    for warning in result.warnings:
        print(f"[WARN] {warning}")
    for error in result.errors:
        print(f"[ERROR] {error}")

    if result.errors:
        print(f"\n目录验证失败：{len(result.errors)} 个错误，{len(result.warnings)} 个提醒。")
        return 1

    print(
        f"目录验证通过：{len(papers)} 篇独立论文、{len(valid_codes)} 个统一子问题；"
        "summary/detail、作者、备注、站内引用、单位、本地 PDF 与两份生成物均一致。"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
